// Using pure JSON Schema

export const definitions = {
  ParcelStatus: {
    $id: '#ParcelStatus', // JSON Schema standard for local $id
    type: 'string',
    enum: ['pending', 'shipped', 'delivered', 'cancelled'],
  },
  PaymentStatus: {
    $id: '#PaymentStatus',
    type: 'string',
    enum: ['unpaid', 'paid', 'partial'],
  },
  ParcelCore: {
    $id: '#ParcelCore',
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      parcelRef: { type: 'string' },
      receiveDate: { type: 'string', format: 'date-time' },
      customerCode: { type: 'string' },
      shipment: { type: 'string' },
      estimate: { type: 'number' },
      status: { $ref: '#ParcelStatus' },
      cnTracking: { type: 'string' },
      volume: { type: 'number' },
      weight: { type: 'number' },
      freight: { type: 'number' },
      deliveryMethod: { type: 'string' },
      thTracking: { type: 'string' }, // Optional: not in required list
      paymentStatus: { $ref: '#PaymentStatus' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: [
      'id',
      'parcelRef',
      'receiveDate',
      'customerCode',
      'shipment',
      'estimate',
      'status',
      'cnTracking',
      'volume',
      'weight',
      'freight',
      'deliveryMethod',
      // thTracking is optional
      'paymentStatus',
      'createdAt',
      'updatedAt',
    ],
  },
};

export const ListParcelsQuerySchema = {
  type: 'object',
  properties: {
    page: { type: 'integer', minimum: 1, default: 1 },
    pageSize: { type: 'integer', minimum: 1, maximum: 100, default: 10 },
    status: {
      anyOf: [
        { $ref: 'definitions#ParcelStatus' }, // Reference shared definition
        { type: 'string', const: 'all' },
      ],
    },
    paymentStatus: {
      anyOf: [
        { $ref: 'definitions#PaymentStatus' }, // Reference shared definition
        { type: 'string', const: 'all' },
      ],
    },
    trackingNo: { type: 'string' },
    dateFrom: { type: 'string', format: 'date' },
    dateTo: { type: 'string', format: 'date' },
    customerCode: { type: 'string' },
  },
  // All properties are optional by default in query parameters unless specified in required
};

export const ListParcelsResponseSchema = {
  type: 'object',
  properties: {
    parcels: {
      type: 'array',
      items: { $ref: 'definitions#ParcelCore' }, // Reference shared definition
    },
    total: { type: 'integer' },
    page: { type: 'integer' },
    pageSize: { type: 'integer' },
  },
  required: ['parcels', 'total', 'page', 'pageSize'],
};

export const GetParcelByIdParamsSchema = {
  type: 'object',
  properties: {
    id: { type: 'string', format: 'uuid' },
  },
  required: ['id'],
};

// Response is a single ParcelCore
export const GetParcelByIdResponseSchema = { $ref: 'definitions#ParcelCore' }; // Reference shared definition

export const UpdateParcelStatusParamsSchema = {
  type: 'object',
  properties: {
    id: { type: 'string', format: 'uuid' },
  },
  required: ['id'],
};

export const UpdateParcelStatusBodySchema = {
  type: 'object',
  properties: {
    status: { $ref: 'definitions#ParcelStatus' }, // Reference shared definition
    notify: { type: 'boolean', default: false },
  },
  required: ['status'],
};

// Response is the updated ParcelCore
export const UpdateParcelStatusResponseSchema = { $ref: 'definitions#ParcelCore' }; // Reference shared definition

export const ErrorSchema = {
  type: 'object',
  properties: {
    statusCode: { type: 'integer' },
    error: { type: 'string' },
    message: { type: 'string' },
  },
  required: ['statusCode', 'error', 'message'],
};

// The TypeScript types previously generated by Static<TypeBoxSchema> will be removed.
// Fastify can infer types for handlers, or if complex types are needed for services/controllers
// they might need to be defined as separate interfaces. For now, we remove them.
